# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
  push:
  #  branches: [ main ]
  pull_request:
  #  branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
        
    - name: Build with Maven
      run: |
        set
        mvn versions:set "-DnewVersion=${{ env.GITVERSION_SEMVER }}"
        mvn -B package --file pom.xml
        ls -l target
        
    - uses: actions/upload-artifact@v2
      with:
        name: OoliteAddonScanner
        path: target/OoliteAddonScanner-1.0-SNAPSHOT-executable.zip
      
    - name: Create Prerelease
      if: github.ref != 'refs/heads/main'
      id: create_prerelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.GITVERSION_SEMVER }}"
        prerelease: true
        title: "OoliteAddonScanner"
        files: |
          target/*.zip
          target/*.tar.gz
      
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.GITVERSION_SEMVER }}"
        prerelease: true
        title: "OoliteAddonScanner"
        files: |
          target/*.zip
          target/*.tar.gz
