name: Scan AddOns
on: workflow_dispatch
      
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        # inspired by https://github.com/marketplace/actions/download-workflow-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: maven.yml
          name: OoliteAddonScanner
          
      - name: Install AddonScanner
        run: |
          unzip OoliteAddonScanner-1.0-SNAPSHOT-executable.zip
          find
          
      - name: Run AddonScanner
        run: |
          java -jar OoliteAddonScanner-1.0-SNAPSHOT/OoliteAddonScanner-1.0-SNAPSHOT.jar
          